### ISSUE TITLE
Deprecate use of `Variable` in symbolic expressions, split into `SpatialConstant` and `DiscretizedVariable`

### ISSUE THREAD

**Issue by inducer** [inducer/pytential#116]
cc @isuruf 

@alexfikl what do you think? The basic issue we're trying to solve is that the mappers in the guts need to be able to tell whether something can be pulled out of a derivative or not.

**Comment by alexfikl** [comment]
Sounds good to me.

Why not keep `Variable` as is and just introduce a `SpatialConstant`? The new names are definitely clearer, so just curious of other benefits.

**Comment by inducer** [comment]
For me, the reasoning behind deprecating `Variable` is that it is a straightforward way to flag all the places where a distinction needs to be made where one wasn't previously made. Of course, all `Variable`s need to be treated as spatially varying if nothing else is known.

@isuruf, what do you think?

**Comment by isuruf** [comment]
Agreed. It's good to warn to the user that `Variable`s are not considered a `SpatialConstant` and declaring so would get performance benefits.

**Comment by isuruf** [comment]
On the other hand, for the use-cases we have we know that `k, mu, nu` are `SpatialConstant` given that they are `lp.ValueArg` from for eg: https://github.com/inducer/sumpy/blob/596ae41eb8703b0c399c889408a1551c2fe109d5/sumpy/kernel.py#L624

**Comment by inducer** [comment]
Eh, I think that's digging too deep. Even if you were volunteering to write the analysis that figures this out, I'm not sure I'd want it. For one, it's sumpy-specific, but we're trying hard to move towards allowing more than one backend. I think it's not too much to ask of the user to tell us whether a variable is a scalar or not.

**Comment by isuruf** [comment]
There are two ways that a user can currently give constants such as `mu`.
1. `bind(sym.IntG(StokesletKernel(2), mu=2))`
2. `bind(sym.IntG(StokesletKernel(2), mu=var("w")), w=2)`

For the second case I agree that the user should say it is a `SpatialConstant`. For the first use-case, when converting the StokesletKernel to a BiharmonicKernel, I'm creating a new Variable "mu". Same for normal derivative vectors. Not sure how we can proceed without doing the analysis.

**Comment by alexfikl** [comment]
> For the second case I agree that the user should say that `w` is a `SpatialConstant`. For the first use-case, when converting the StokesletKernel to a BiharmonicKernel, I'm creating a new Variable "mu". Same for normal derivative vectors. Not sure how we can proceed without doing the analysis.

Can we teach `pymbolic` about constants? So that `sumpy` can mark the newly created variable as a constant itself?
