### ISSUE TITLE
Is dep_source in MatrixBuilderBase used?

### ISSUE THREAD

**Issue by isuruf** [inducer/pytential#189]
Seems like `dep_source` is set but is not read by anyone.
`dep_discr` is only read for its `ndofs` value.

cc @alexfikl

**Comment by alexfikl** [comment]
Yeah, `dep_source` doesn't seem used anymore.

Vague recollection is that we added the `GeometryCollection` and used `get_geometry` with the `dofdesc` of the expression when the source geometry was required, so `dep_source` became redundant. I expect that `dep_discr` can probably be removed too with a bit of work.. it seems to only be used to create an identity matrix for the density like you said.

**Comment by alexfikl** [comment]
@isuruf Was this fixed by #190? 

Not sure how to get rid of `dep_discr` too, since it's used in `map_variable`, which doesn't know on which geometry it's defined.

**Comment by inducer** [comment]
I think it was. I'll close this. @isuruf reopen if there's a lingering concern.

**Comment by isuruf** [comment]
Thanks @alexfikl
