### ISSUE TITLE
`test_beltrami_convergence` for 3D Yukawa seems to have be failing

### ISSUE THREAD

**Issue by inducer** [inducer/pytential#205]
Sample CI log: https://gitlab.tiker.net/inducer/pytential/-/jobs/559888#L728

@alexfikl Any clue what might be happening?

It's not clear that it ever passed, as scheduled builds on Gitlab weren't running for a *long* while without anyone noticing. (fixed a while ago, happened in connection with the `master` -> `main` branch name change) https://gitlab.tiker.net/inducer/pytential/-/pipelines?scope=all

**Comment by alexfikl** [comment]
The tests I did in #115 seem to be focused on the 2D case (since that was running on the CI), so not quite sure about the 3D case. I'll check it out and see what doesn't work.
