### ISSUE TITLE
Mismatched python version in tests

### ISSUE THREAD

**Issue by alexfikl** [inducer/pytential#227]
I was *casually* browsing some CI logs and noticed some weird python versions. For example in the `mypy` job:
https://github.com/inducer/pytential/actions/runs/8585851526/job/23527688448

1. It's setup to run on `3.x`, which the `setup-python` action correctly sets up to
	```
	> Installed versions
  	Successfully set up CPython (3.12.2)
	```
2. Then `conda` takes over and installs
	```
	  + python                        3.10.14  hd12c33a_0_cpython  conda-forge     Cached
	```
3. Then there's some `conda update` that gets it up to
	````
	python                    3.11.8          hab00c5b_0_cpython    conda-forge
	````
4. Then all additional dependencies are downloaded for `py311` e.g.
	```
	Downloading pyrsistent-0.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (120 kB)
	```

So the tests seem to be running on 3.11 instead of 3.12. This seems to be the case for all the tests whether they mention a python version or not. As far as I can tell, this is an issue with the conda environment. Any ideas what might be wrong there?

**Comment by inducer** [comment]
Conda jobs should probably not have `setup-python` in the first place. And I don't want to be in the business of prescribing what Python version Conda installs, that seems like too much work.

**Comment by alexfikl** [comment]
That's fair, but it makes the CI a bit confusing. E.g. this `flake8` test
```
                # matches compat target in setup.py
                python-version: '3.8'
```
doesn't actually run on 3.8.

**Comment by inducer** [comment]
#228?
