### ISSUE TITLE
Discussion: Deprecate overloading `__new__` for operator application?

### ISSUE THREAD

**Issue by inducer** [inducer/pytential#246]
Suppose `x` is a numpy object array of densities.

Now: `S(x)` returns a vector of single-layer potentials.

A possible future: `componentwise(S, x)` returns a vector of single-layer potentials.

Context/motivation: https://github.com/inducer/pytential/pull/245#discussion_r1844481562

cc @alexfikl

**Comment by alexfikl** [comment]
I would argue for:
* Adding a `num_reference_derivative` function for the corresponding `NumReferenceDerivative` class that does this vectorization. Similarly for the other overloaded classes.
* Adding a little `@componentwise` decorator (or something like that) that automatically does that (a la `for_each_kernel` in loopy).

I don't know if being explicit with `componentwise(Something, operand, **kwargs)` in a lot of places is worth it..

**Comment by inducer** [comment]
D'oh! Yes, you're right of course. That sounds like a good plan. Let's deprecate the `__new__` thing and have a vectorizing function.
