### ISSUE TITLE
Betterplane test case dies in gmsh

### ISSUE THREAD

**Issue by inducer** [inducer/pytential#5]
```
python test_scalar_int_eq.py 'test_integral_equation(cl._csc, BetterplaneIntEqTestCase(30, "dirichlet", +1), visualize=True)'
```
dies with some gmsh nonsense.

cc @xywei @gaohao95

**Comment by xywei** [comment]
The test runs fine for me. I am using `gmsh 4.4.1` from conda-forge.

**Comment by inducer** [comment]
I'm on gmsh 4.4.1 from Debian, which complains:
```
pytools.prefork.ExecError: error invoking 'gmsh -o output.msh -nopopup -format msh2 -string Geometry.OCCTargetUnit='MM'; -2 /tmp/tmps2afbr8h/temp.geo': status 1 invoking 'gmsh -o output.msh -nopopup -format msh2 -string Geometry.OCCTargetUnit='MM'; -2 /tmp/tmps2afbr8h/temp.geo': Error   : Unknown field type "Attractor"
Error   : '/tmp/tmps2afbr8h/temp.geo', line 19 : Cannot create field 1 of type 'Attractor'
Error   : '/tmp/tmps2afbr8h/temp.geo', line 20 : No field with id 1
Error   : '/tmp/tmps2afbr8h/temp.geo', line 21 : No field with id 1
[...]
```
How come your gmsh 4.4.1 knows about "Attractor" refinement fields and mine doesn't?

**Comment by xywei** [comment]
According to http://gmsh.info/doc/texinfo/gmsh.html, quote:

> Attractor is deprecated: use Distance instead.

It might be that the Debian build removed support for it.

**Comment by inducer** [comment]
Good catch! Changing these to `Distance` addressed the issue. Do you know when they introduced `Distance`?

**Comment by xywei** [comment]
I didn't find it in the changelog either. Though [this commit](https://gitlab.onelab.info/gmsh/gmsh/commit/6675584f217a3aee857984919802e7794a2f0672) claims to deprecate `Attractor`
