### ISSUE TITLE
Unstable evaluation of layer potential source derivatives onto volume targets

### ISSUE THREAD

**Issue by xywei** [inducer/pytential#53]
When evaluating a source derivative onto a set of volume targets, the results at some near-surface target points are appear unstable unless the source mesh is extremely refined.

Example with Laplace kernel:
- with "bad points":
 
  ![image](https://user-images.githubusercontent.com/1251311/106610726-b5eb5f80-652c-11eb-9292-f5c4fc618169.png)

- refining the source mesh 6 extra times yields results without "bad points":

  ![image](https://user-images.githubusercontent.com/1251311/106610776-c4d21200-652c-11eb-9ccd-c0af549cfb99.png)

Here is a reproducing scirpt: [boundary-layer.py](https://gitlab.tiker.net/inducer/pytential/uploads/7a559c406a73e8d451689842cb2bb5a5/boundary-layer.py)

More observations:
- No bad points when evaluating raw potentials or target derivatives.
- No bad points are observed when evaluating onto surface targets.

**Comment by inducer** [comment]
FWIW, only direct evaluation mode was affected by this, and should now be fixed.
